#!/usr/bin/env bash
#install nginx in server
apt-get update
apt-get -y install nginx


chown -R "$USER":"$USER" /var/www/


printf %s "Hello World!\n" > /var/www/html/index.nginx-debian.html

nginx -s reload
