#!/usr/bin/env bash
#install nginx in server
apt-get update
apt-get -y install nginx

mkdir -p /var/www/html
touch /var/www/html/index.html

printf %s "Hello World!\n" > /var/www/html/*

nginx -s reload
