#!/usr/bin/env bash
#install nginx in server
sudo apt-get update
sudo apt-get -y install nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html

sudo printf %s "Hello World!\n" > /var/www/html/*

sudo nginx -s reload
