#!/usr/bin/env bash
#install nginx in server
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart

service nginx reload

sudo service nginx start
